production:
  site: cardspring
  use_ssl: true
  rooms:
  - Devs
  api_key: 5bcf37e2b5c4d5bb7b55750307239640102cc44b
  username: cardspring-bot
  nickname: bot
  twitter_feed: ''
  twitter_hide_replies: false
  enable_plugins:
    - accountability
    - austin
    - beer
    - beijing_tally
    - boop
    - bruce
    - calvin
    - chuck
    - dilbert
    - excuse
    - fail
    - figlet
    - fun
    - garfield
    - generic_search
    - help
    - infobot
    - insult
    - jira
    - lolcats
    - our_quotes
    - quote
    - schneier
    - seen
    - signal_filter
    - svn
    - twitter_echo
    - xkcd
  jira_urls: https://cardspring.atlassian.net
